### ISSUE TITLE
[Feature Request] address bar pin/unpin tab icon

### ISSUE THREAD

**Issue by circcc** [jyssh/pin-unpin-tab#28]
![Pin-Tab-option-in-Page-Actions-Menu-Firefox](https://github.com/jyshb/pin-unpin-tab/assets/72944033/2f246ab7-181b-4ad8-885a-427239d94765)
In previous versions of Firefox, it could be pinned to the address bar through the right-click menu of the Pin Tab menu in the Page Actions menu. This feature has removed so I am using the Pin Unpin Tab extension, but I prefer the address bar button rather than the toolbar button.

**Comment by jyssh** [comment]
I loved to put the icons in url bar too. Sadly that customisable feature was removed a couple of years back, as far as I can remember.

Here is a relevant link: https://blog.mozilla.org/en/products/firefox/new-firefox-coming-june-1/

Now, while Firefox devs have put a few icons there, users cannot seem to customise that strip anymore.

Feel free to reopen if you find an add-on that's able to put its icon there.
